[package]
name = "pv_cobra_micdemo"
version = "0.1.1"
edition = "2018"

[dependencies]
chrono = "0.4.23"
clap = "2.33.3"
ctrlc = "3.1.9"
hound = "3.5.0"
itertools = "0.10.1"
pv_cobra = "=2.0.2"
pv_recorder = "=1.2.1"
