name: .NET Demos

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'demo/dotnet/**'
      - '!demo/dotnet/README.md'
      - 'res/audio/**'
      - '.github/workflows/dotnet-demos.yml'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/dotnet/**'
      - '!demo/dotnet/README.md'
      - 'res/audio/**'
      - '.github/workflows/dotnet-demos.yml'

defaults:
  run:
    working-directory: demo/dotnet/CobraDemo

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        device: [cpu, cpu:1]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Package restore
      run: dotnet restore

    # *********** REMOVE AFTER RELEASE **********************
    - name: Pack binding for local ref
      run: dotnet pack -c Release
      working-directory: binding/dotnet

    - name: Add binding to demo
      run: dotnet add package -s ../../../binding/dotnet/Cobra/bin/Release Cobra
    # ******************************************************

    - name: Dotnet build mic demo
      run: dotnet build -c MicDemo.Release -- --device ${{ matrix.device }}

    - name: Dotnet build file demo
      run: dotnet build -c FileDemo.Release

    - name: Run Dotnet file demo
      run: dotnet run -c FileDemo.Release -- --input_audio_path ../../../res/audio/sample.wav --access_key ${{secrets.PV_VALID_ACCESS_KEY}} --device ${{ matrix.device }}

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        device: [best]
        machine: [rpi3-32, rpi3-64, rpi4-32, rpi4-64, rpi5-64, pv-windows-arm64]
        include:
          - device: gpu
            machine: pv-linux
          - device: gpu
            machine: pv-windows
          - device: gpu
            machine: pv-ios

    steps:
    - uses: actions/checkout@v3

    - name: Package restore
      run: dotnet restore

    # *********** REMOVE AFTER RELEASE **********************
    - name: Pack binding for local ref
      run: dotnet pack -c Release
      working-directory: binding/dotnet

    - name: Add binding to demo
      run: dotnet add package -s ../../../binding/dotnet/Cobra/bin/Release Cobra
    # ******************************************************

    - name: Dotnet build mic demo
      run: dotnet build -c MicDemo.Release

    - name: Dotnet build file demo
      run: dotnet build -c FileDemo.Release

    - name: Run Dotnet file demo
      run: dotnet run -c FileDemo.Release -- --input_audio_path ../../../res/audio/sample.wav --access_key ${{secrets.PV_VALID_ACCESS_KEY}} --device ${{ matrix.device }}
